### ISSUE TITLE
Backlog of pan gesture commands on Windows

### ISSUE THREAD

**Issue by whodges** [vapolia/MauiGestures#3]
I was wondering you could change the line (or add an option to effect the change) in `PlatformGestureEffect.ControlOnPointerMoved` in `Platforms\Windows\PlatformGestureEffect.cs` from:

`detector.ProcessMoveEvents(pointerRoutedEventArgs.GetIntermediatePoints(Control ?? Container));`

to something like:

`detector.ProcessMoveEvents(new List<PointerPoint>() { pointerRoutedEventArgs.GetCurrentPoint(Control ?? Container) });`

The reason being that I find `GetIntermediatePoints` returns several points, and if a particular draw operation takes a little bit of time, you end up with a delayed response where an image that you're panning can keep moving as the application tries to catch up with the move events in the queue.  Instead, I think a coalescing approach should taken (or, at least, the option should be given), and all of those other points except the most recent should be discarded.

This only affects the Windows platform, as all the other platforms seems to go the coalescing route.

Otherwise I've found this library to be absolutely fantastic and indispensable given the current state of gesture operations in .NET MAUI.

**Comment by softlion** [comment]
So your issue is, you are using the PanPointCommand, and you are receiving too many points per event, am I right ?

I created a new property ReturnAllPointsOnWindows which is false by default. So you should see your new behavior by default in 1.0.6
Can you test the prerelease version of 1.0.6 which is already on nuget ?

**Comment by whodges** [comment]
Yep, you got it!  Just tried it and it works great.  Thank you for such a quick response!

**Comment by softlion** [comment]
1.0.6 stable released
