### ISSUE TITLE
Detect finger down

### ISSUE THREAD

**Issue by cdecron** [vapolia/MauiGestures#4]
Hello, thank you for this library :)
Does it provide a way to detect when the user finger touches a view? And when it's moved and released?
If it doesn't, maybe someone know a MAUI library that has this feature?

Thank you :)

**Comment by softlion** [comment]
yes, check PanCommand  and PanPointCommand

**Comment by cdecron** [comment]
Hello, thank you for your answer, but I tried and didn't manage to make it work... However I found another library which does what I need ([MR.Gestures](https://www.mrgestures.com/) for people who needs same features as me).
Thank you!
